# Technical Project Assignment

Task 1: Data Ingestion 
1. Load all three CSV files (sales_data.csv, products.csv, stores.csv) into pandas DataFrames. 
Print the shape and first 5 rows of each. 
2. Check for missing values in all three DataFrames and print a summary of which columns 
have null values.

## Answer 1

In [6]:
# Firstly we have import pandas to run further functions.
import pandas as pd 

# Using pd.read function to import dataframes.
df1 = pd.read_csv("C:\\Users\\Admin\\Downloads\\sales_data.csv")
df2 = pd.read_csv("C:\\Users\\Admin\\Downloads\\products.csv")
df3 = pd.read_csv("C:\\Users\\Admin\\Downloads\\stores.csv")

In [7]:
# Determining the shape of the Dataframes to see how many columns and rows are present in a dataframe. 
df1.shape

(15, 6)

In [8]:
# Printing first 5 rows.
df1.head()

  sale_id store_id product_id  quantity  sale_date  amount
0      s1      st1         p1       2.0   9/1/2025  1000.0
1      s2      st2         p2       1.0   9/2/2025   800.0
2      s3      st3         p3       3.0   9/5/2025   450.0
3      s4      st4         p4       NaN  9/23/2025  1200.0
4      s5      st5         p5       5.0  9/21/2025     NaN

In [9]:
# Determining the shape of the Dataframes.
df2.shape

(15, 4)

In [10]:
# Printing first 5 rows.
df2.head()

  product_id  product_name     category  price
0         p1        Laptop  Electronics    500
1         p2    Smartphone  Electronics    800
2         p3      Notebook   Stationery    150
3         p4        Tablet  Electronics   1200
4         p5  Office Chair    Furniture    250

In [48]:
# Determining the shape of the Dataframes.
df3.shape

(15, 4)

In [11]:
# Printing first 5 rows.
df3.head()

  store_id  store_name       city  region
0      st1  RetailMart     Jaipur   North
1      st2  RetailMart      Delhi  North
2      st3  RetailMart     Mumbai    West
3      st4  RetailMart       Pune    West
4      st5  RetailMart  Bengaluru   South

## Answer 2

In [12]:
# Checking for null values in dataframes
print(df1.isnull().sum())

sale_id       0
store_id      0
product_id    0
quantity      3
sale_date     0
amount        2
dtype: int64

In [13]:
# Checking for null values in dataframes
print(df2.isnull().sum())

product_id      0
product_name    0
category        0
price           0
dtype: int64

In [14]:
# Checking for null values in dataframes
print(df3.isnull().sum())

store_id      0
store_name    0
city          0
region        0
dtype: int64

Task 2: Data Cleaning 
3. Remove all duplicate rows from sales_data. Print how many duplicates were found and 
removed. 
4. Fill missing values in the 'quantity' column with 0 and drop rows where 'amount' is NULL. 
Print the cleaned DataFrame shape. 
5. Convert the 'sale_date' column to proper datetime format and the 'amount' column to float 
data type.

## Answer 3

In [15]:
# Checking for duplicate rows in the dataframe and printing it.
duplicate_rows = df1.duplicated().sum()
print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 0

#### Hence there are no duplicate rows so we don't have to drop any of the rows.So zero duplicate rows found and zero duplicate rows were removed.

But if there were some duplicate rows we can use drop function!!
df1 = df1.drop_duplicates()
Using this function we can drop all the duplicated rows easily.|

## Answer 4

In [16]:
# Filling missing values in quantity with 0.
df1["quantity"] = df1["quantity"].fillna(0)

# Dropping rows where amount is NULL or NAN.
df1 = df1.dropna(subset = ["amount"])

# So to check if our dataframe is cleaned or not we will check the shape of our new cleaned dataframe.
df1.shape

(13, 6)

#### So here we can clearly see that out of 15 rows there are only 13 rows left that means we have cleaned our dataframe.

## Answer 5

In [17]:
# Firstly checking if I need to covert 'sale_date' column to proper datetime format and 'amount' column to float data type.
print(df1.dtypes)

sale_id        object
store_id       object
product_id     object
quantity      float64
sale_date      object
amount        float64
dtype: object

# Here we can clearly see that they are already in their correct format so I don't need to change them.
But if I need to change them I can change those columns like this :
For datetime - df1["sale_date"] = pd.to_datetime(df1["sale_date"])
For float - df1["amount"] = df1["amount"].astype(float)

Task 3: Data Transformation 
6. Merge all three DataFrames into one final DataFrame using appropriate JOIN on store_id and 
product_id. Print the final merged DataFrame. 
7. Add a new column 'total_revenue' = quantity × price. Use NumPy to calculate and print the 
mean, max, and min of total_revenue. 
8. Group the data by 'city' and find the total revenue generated per city. Sort the result in 
descending order.

## Answer 6

In [18]:
# So we are going to use Inner join to join all the dataframes because we only want the records where the store_id and product_id exist in all three dataframes.

# Now firstly joining 'sales_data' and 'products' DataFrames together.
merged_df = pd.merge(df1, df2, on="product_id", how="inner")

# Now we are going to join all the three Dataframes together.
final_df = pd.merge(merged_df, df3, on="store_id", how="inner")

# Now we will see if they are joined toghter successfully or not.So we are going to print our final merged dataframe.
final_df

,sale_id,store_id,product_id,quantity,sale_date,amount,product_name,category,price,store_name,city,region
0,s1,st1,p1,2.0,9/1/2025,1000.0,Laptop,Electronics,500,RetailMart,Jaipur,North
1,s2,st2,p2,1.0,9/2/2025,800.0,Smartphone,Electronics,800,RetailMart,Delhi,North
2,s3,st3,p3,3.0,9/5/2025,450.0,Notebook,Stationery,150,RetailMart,Mumbai,West
3,s4,st4,p4,0.0,9/23/2025,1200.0,Tablet,Electronics,1200,RetailMart,Pune,West
4,s6,st6,p6,2.0,9/15/2025,180.0,Pen,Stationery,90,RetailMart,Chennai,South
5,s7,st7,p7,1.0,9/19/2025,1500.0,Television,Electronics,1500,RetailMart,Hyderabad,South
6,s8,st8,p8,4.0,9/13/2025,200.0,Water bottle,Accessories,30,RetailMart,Kolkata,East
7,s9,st9,p9,2.0,9/18/2025,1000.0,Headphones,Electronics,500,RetailMart,Lucknow,North
8,s10,st10,p10,1.0,9/30/2025,700.0,Keyboard,Electronics,700,RetailMart,Ahemdabad,West
9,s11,st11,p11,2.0,9/25/2025,800.0,Mouse,Electronics,400,RetailMart,Indore,Central
10,s13,st13,p13,2.0,9/17/2025,1900.0,Printer,Electronics,950,RetailMart,Kochi,South
11,s14,st14,p14,0.0,9/5/2025,600.0,Backpack,Accessories,600,RetailMart,Bhopal,Central
12,s15,st15,p15,1.0,9/4/2025,200.0,Calculator,Stationery,200,RetailMart,Patna,East

## Answer 7

In [19]:
# Now I have to add a new cloumn 'total_revenue' which will be the product of 'quantity' and 'price'.
final_df["total_revenue"] = final_df["quantity"] * final_df["price"]

# Now we are going to check if our new column is successfully added or not.
final_df

,sale_id,store_id,product_id,quantity,sale_date,amount,product_name,category,price,store_name,city,region,total_revenue
0,s1,st1,p1,2.0,9/1/2025,1000.0,Laptop,Electronics,500,RetailMart,Jaipur,North,1000.0
1,s2,st2,p2,1.0,9/2/2025,800.0,Smartphone,Electronics,800,RetailMart,Delhi,North,800.0
2,s3,st3,p3,3.0,9/5/2025,450.0,Notebook,Stationery,150,RetailMart,Mumbai,West,450.0
3,s4,st4,p4,0.0,9/23/2025,1200.0,Tablet,Electronics,1200,RetailMart,Pune,West,0.0
4,s6,st6,p6,2.0,9/15/2025,180.0,Pen,Stationery,90,RetailMart,Chennai,South,180.0
5,s7,st7,p7,1.0,9/19/2025,1500.0,Television,Electronics,1500,RetailMart,Hyderabad,South,1500.0
6,s8,st8,p8,4.0,9/13/2025,200.0,Water bottle,Accessories,30,RetailMart,Kolkata,East,120.0
7,s9,st9,p9,2.0,9/18/2025,1000.0,Headphones,Electronics,500,RetailMart,Lucknow,North,1000.0
8,s10,st10,p10,1.0,9/30/2025,700.0,Keyboard,Electronics,700,RetailMart,Ahemdabad,West,700.0
9,s11,st11,p11,2.0,9/25/2025,800.0,Mouse,Electronics,400,RetailMart,Indore,Central,800.0
10,s13,st13,p13,2.0,9/17/2025,1900.0,Printer,Electronics,950,RetailMart,Kochi,South,1900.0
11,s14,st14,p14,0.0,9/5/2025,600.0,Backpack,Accessories,600,RetailMart,Bhopal,Central,0.0
12,s15,st15,p15,1.0,9/4/2025,200.0,Calculator,Stationery,200,RetailMart,Patna,East,200.0

In [20]:
# Now are going to calculate and print the mean, max and min of 'total_revenue' using numpy.

# Firstly I have to import numpy.
import numpy as np

# Finding Mean
mean_val = np.mean(final_df["total_revenue"])

# Finding Max
max_val = np.max(final_df["total_revenue"])

# Finding Min
min_val = np.min(final_df["total_revenue"])

# Now printing them all
print("Mean Total Revenue:", mean_val)
print("Maximum Total Revenue:", max_val)
print("Minimum Total Revenue:", min_val)

Mean Total Revenue: 665.3846153846154
Maximum Total Revenue: 1900.0
Minimum Total Revenue: 0.0

## Answer 8

In [21]:
# Now are going to group the data by 'city' and find the total revenue generated per city.
city_revenue = final_df.groupby("city")["total_revenue"].sum()
city_revenue

city
Ahemdabad     700.0
Bhopal          0.0
Chennai       180.0
Delhi         800.0
Hyderabad    1500.0
Indore        800.0
Jaipur       1000.0
Kochi        1900.0
Kolkata       120.0
Lucknow      1000.0
Mumbai        450.0
Patna         200.0
Pune            0.0
Name: total_revenue, dtype: float64

In [22]:
# Now we are going to sort the result in descending order. 
city_revenue = city_revenue.sort_values(ascending=False)
city_revenue

city
Kochi        1900.0
Hyderabad    1500.0
Jaipur       1000.0
Lucknow      1000.0
Delhi         800.0
Indore        800.0
Ahemdabad     700.0
Mumbai        450.0
Patna         200.0
Chennai       180.0
Kolkata       120.0
Bhopal          0.0
Pune            0.0
Name: total_revenue, dtype: float64

Task 4: Data Loading (SQL) 
9. Load the final cleaned and merged DataFrame into a SQLite database table called 
'retail_sales'. Write the Python code using sqlite3 or sqlalchemy. 
10. Write a SQL query to find the Top 3 best-selling products by total quantity sold from the 
'retail_sales' table.

## Answer 9

In [23]:
# Now we are going to load our final_df into a SQLite database table called 'retail_sales'.

# Firstly we have to import sqlite3 library.
import sqlite3

# Now we are going to make a connection to the SQLite database.
connection = sqlite3.connect("reatil_sales.db")

# Now we are going to load our dataframe into a table called 'reatil_sales'
final_df.to_sql("retail_sales", connection, if_exists="replace", index=False)

13

## Answer 10

In [24]:
# Now we are going to find the top 3 best-selling products by total quantity by writing a sql query.
query = """
SELECT
    product_id,
    product_name,
    SUM(quantity) AS total_quantity_sold
FROM retail_sales
GROUP BY product_id, product_name
ORDER BY total_quantity_sold DESC
LIMIT 3;
"""
# Now we are going to execute the query and store the result in our dataframe.
top_3_products = pd.read_sql_query(query, connection)

# Now we are going to print the result
top_3_products

  product_id   product_name  total_quantity_sold
0         p8  Water bottle                   4.0
1         p3       Notebook                  3.0
2         p1         Laptop                  2.0

Task 5: Reporting & Insights 
11. Write a SQL query to find total revenue per store per day from the 'retail_sales' table. 
12. Using Python, print a summary report showing: Total number of transactions, Total revenue, 
Top selling city, and Top selling product.

## Answer 11

In [25]:
# Now ae are going to write a SQL query to find total revenue per store per day from the 'retail_sales' table.

query = """
SELECT
    store_id,
    store_name,
    sale_date,
    SUM(total_revenue) AS total_revenue
FROM retail_sales
GROUP BY store_id, store_name, sale_date
ORDER BY store_id, sale_date;
"""

# Now we are going to execute the query as well as we will print it.
revenue_per_store = pd.read_sql_query(query, connection)
print(revenue_per_store)

   store_id  store_name  sale_date  total_revenue
0       st1  RetailMart   9/1/2025         1000.0
1      st10  RetailMart  9/30/2025          700.0
2      st11  RetailMart  9/25/2025          800.0
3      st13  RetailMart  9/17/2025         1900.0
4      st14  RetailMart   9/5/2025            0.0
5      st15  RetailMart   9/4/2025          200.0
6       st2  RetailMart   9/2/2025          800.0
7       st3  RetailMart   9/5/2025          450.0
8       st4  RetailMart  9/23/2025            0.0
9       st6  RetailMart  9/15/2025          180.0
10      st7  RetailMart  9/19/2025         1500.0
11      st8  RetailMart  9/13/2025          120.0
12      st9  RetailMart  9/18/2025         1000.0

## Answer 12

In [26]:
# Now using python summary report showing: 

# Total number of transactions
total_transactions = len(final_df)

# Total revenue
total_revenue = final_df["total_revenue"].sum()

# Top Selling City
top_city = (
    final_df.groupby("city")["total_revenue"]
    .sum()
    .idxmax()
)

# Top Selling Product
top_product = (
    final_df.groupby("product_name")["quantity"]
    .sum()
    .idxmax()
)

# Now we are going to print them all in the form of a summary report
print("Summary Report")
print(f"Total Number of Transactions : {total_transactions}")
print(f"Total Revenue : {total_revenue}")
print(f"Top Selling City : {top_city}")
print(f"Top Selling Product : {top_product}")

Summary Report
Total Number of Transactions : 13
Total Revenue : 8650.0
Top Selling City : Kochi
Top Selling Product : Water bottle

Task 6: Pipeline & Error Handling 
13. Write a Python function called run_pipeline() that runs all the above steps (load → clean → 
transform → load to DB) in one single function call. 
14. Add basic error handling (try-except) to your pipeline so that if any file is missing, it prints a 
proper error message instead of crashing.

## Answer 13

In [31]:
# Now we are going define a function called 'run_pipeline' that will runs all the above steps together.
def run_pipeline():
    # Load files
    df1 = pd.read_csv("C:\\Users\\Admin\\Downloads\\sales_data.csv")
    df2 = pd.read_csv("C:\\Users\\Admin\\Downloads\\products.csv")
    df3 = pd.read_csv("C:\\Users\\Admin\\Downloads\\stores.csv")

    print("Files loaded successfully.")

    # Data Cleaning
    duplicate_count = df1.duplicated().sum()
    df1 = df1.drop_duplicates()

    df1["quantity"] = df1["quantity"].fillna(0)
    df1 = df1.dropna(subset=["amount"]).copy()

    print(f"Duplicates Removed : {duplicate_count}")
    print("Data cleaned successfully.")

    # Merging DataFrames together
    merged_df = pd.merge(df1, df2, on="product_id", how="inner")
    final_df = pd.merge(merged_df, df3, on="store_id", how="inner")

    # Transforming Data
    final_df["total_revenue"] = final_df["quantity"] * final_df["price"]

    print("Transformation completed.")

    # Final Step Loading DataFrame into a Database
    connection = sqlite3.connect("reatil_sales.db")
    final_df.to_sql("retail_sales", connection, if_exists="replace", index=False)

    print("Data loaded successfully into SQLite database.")
    print("Pipeline executed successfully!")

    return final_df

In [33]:
final_df = run_pipeline()

Files loaded successfully.
Duplicates Removed : 0
Data cleaned successfully.
Transformation completed.
Data loaded successfully into SQLite database.
Pipeline executed successfully!

## Answer 14

In [39]:
# Adding a basic error handling (try-except) to our pipeline

def run_pipeline():
    try:
        # Load files
        df1 = pd.read_csv("C:\\Users\\Admin\\Downloads\\sales_data.csv")
        df2 = pd.read_csv("C:\\Users\\Admin\\Downloads\\products.csv")
        df3 = pd.read_csv("C:\\Users\\Admin\\Downloads\\stores.csv")

        print("Files loaded successfully.")

        # Data Cleaning
        duplicate_count = df1.duplicated().sum()
        df1 = df1.drop_duplicates()

        df1["quantity"] = df1["quantity"].fillna(0)
        df1 = df1.dropna(subset=["amount"]).copy()

        print(f"Duplicates Removed : {duplicate_count}")
        print("Data cleaned successfully.")

        # Merging DataFrames together
        merged_df = pd.merge(df1, df2, on="product_id", how="inner")
        final_df = pd.merge(merged_df, df3, on="store_id", how="inner")

        # Transforming Data
        final_df["total_revenue"] = final_df["quantity"] * final_df["price"]

        print("Transformation completed.")

        # Final Step Loading DataFrame into a Database
        connection = sqlite3.connect("reatil_sales.db")
        final_df.to_sql("retail_sales", connection, if_exists="replace", index=False)

        print("Data loaded successfully into SQLite database.")
        print("Pipeline executed successfully!")

        return final_df

    except FileNotFoundError as e:
         print("Error: One or more CSV files were not found.")
         print(e)
        
    except Exception as e:
        print("An unexpected error occurred:")
        print(e)

### So finally I have completed the Technical Project Assignment.